"""Generate the frontend model contract from Pydantic serialization JSON Schemas."""

import json
from pathlib import Path

from agent_trace_review.models import Evaluation, Run

ROOT = Path(__file__).resolve().parents[1]


def ts(schema):
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(ts(s) for s in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts(schema['items'])}>"
    if kind == "object":
        if "properties" in schema:
            required = schema.get("required", [])
            return (
                "{\n"
                + "\n".join(
                    f"  {json.dumps(k)}{'' if k in required else '?'}: {ts(v)};"
                    for k, v in schema["properties"].items()
                )
                + "\n}"
            )
        additional = schema.get("additionalProperties", {})
        return f"Record<string, {ts(additional) if isinstance(additional, dict) else 'unknown'}>"
    return {
        "string": "string",
        "number": "number",
        "integer": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


definitions = {}
schemas = {}
for model in (Run, Evaluation):
    schema = model.model_json_schema(mode="serialization")
    schemas[model.__name__] = schema
    definitions.update(schema.pop("$defs", {}))
    definitions[model.__name__] = schema
target = ROOT / "web/src/generated"
target.mkdir(parents=True, exist_ok=True)
(target / "models.ts").write_text(
    "// Generated by scripts/generate_types.py. Do not edit.\n"
    + "\n\n".join(f"export type {name} = {ts(schema)}" for name, schema in definitions.items())
    + "\n"
)
